# Generated by Django 5.1.5 on 2025-01-24 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_alter_todo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='todo/%Y/%m/%d', verbose_name='이미지'),
        ),
    ]
