# Generated by Django 5.1.5 on 2025-01-23 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_remove_todo_modified_at_todo_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='updated_at',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='updated_at',
            new_name='modified_at',
        ),
    ]
