# Generated by Django 5.1.5 on 2025-01-23 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_rename_updated_at_comment_modified_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='authro',
            new_name='author',
        ),
    ]
